global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "otel collector"
    scrape_interval: 1s
    static_configs:
      - targets: ['otel-collector:8889']
